#!/bin/bash

#
# config file to include in all other scripts
#

#-----------------------------------------------------------------

# General config
USER="satoshi"
HOME_DIR="/home/${USER}"
DOWNLOAD_DIR="${HOME_DIR}/downloads"
LOCAL_IP=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
#RELEASE_CODE=$(awk -F"[)(]+" '/VERSION=/ {print $2}' /etc/os-release)
ARCH=$(dpkg --print-architecture)
#ARCHITECTURE=$(lscpu | egrep "Architecture" | sed s/"          "/" "/g | cut -d ":" -f 2 | xargs)
RELEASE_CODE=$(grep VERSION_CODENAME /etc/os-release | cut -d "=" -f 2)

#-----------------------------------------------------------------

# System config
INSTALL_PKGS="toilet rsync curl gpg git sudo apt-transport-https nginx libnginx-mod-stream mariadb-server mariadb-client ca-certificates gnupg tmux lsb-release ncdu colorized-logs jq make gcc g++"
# libnginx-mod-stream needed in debian12
APT_SOURCES_DIR="/etc/apt/sources.list.d"
KEYRINGS_DIR="/etc/apt/keyrings"
NODEJS_VERSION="20"
NODEJS_LIST_FILE="${APT_SOURCES_DIR}/nodesource.list"
NODEJS_KEYRING_FILE="${KEYRINGS_DIR}/nodesource.gpg"
NPM_UPD_VER="10.8.1"
TOR_LIST_FILE="${APT_SOURCES_DIR}/tor.list"
TOR_KEYRING_FILE="${KEYRINGS_DIR}/tor-archive-keyring.gpg"
TORRC_CONF_FILE="/etc/tor/torrc"
TORSOCKS_CONF_FILE="/etc/tor/torsocks.conf"
NGINX_CONF_FILE="/etc/nginx/nginx.conf"
NGINX_SNIPPETS_DIR="/etc/nginx/snippets"
NGINX_STREAMS_DIR="/etc/nginx/streams-enabled"
NGINX_WEBROOT_DIR="/var/www/html"

#-----------------------------------------------------------------

# Bitcoind config
BITCOIN_VERSION="27.1"
BITCOIN_DOWNLOAD_DIR="${DOWNLOAD_DIR}/Bitcoin"
BITCOIN_DIR="${HOME_DIR}/.bitcoin"
BITCOIN_CONF_FILE="${BITCOIN_DIR}/bitcoin.conf"
BITCOIN_LOG_FILE="${BITCOIN_DIR}/debug.log"
BITCOIN_SERVICE="bitcoind.service"
BITCOIN_SERVICE_FILE="/etc/systemd/system/${BITCOIN_SERVICE}"

#-----------------------------------------------------------------

# Fulcrum config
FULCRUM_VERSION="1.11.0"
FULCRUM_DOWNLOAD_DIR="${DOWNLOAD_DIR}/Fulcrum"
FULCRUM_DIR="${HOME_DIR}/fulcrum"
FULCRUM_DATA_DIR="${HOME_DIR}/fulcrum_db"
FULCRUM_CONF_FILE="${FULCRUM_DIR}/fulcrum.conf"
FULCRUM_SERVICE="fulcrum.service"
FULCRUM_SERVICE_FILE="/etc/systemd/system/${FULCRUM_SERVICE}"

#-----------------------------------------------------------------

# Mempool config
MEMPOOL_VERSION="2.5.0"
MEMPOOL_DIR="${HOME_DIR}/mempool"
MEMPOOL_DB="mempool"
MEMPOOL_BACKEND_DIR="${MEMPOOL_DIR}/backend"
MEMPOOL_FRONTEND_DIR="${MEMPOOL_DIR}/frontend"
MEMPOOL_BACKEND_CONF="${MEMPOOL_BACKEND_DIR}/mempool-config.json"
MEMPOOL_FRONTEND_CONF="${MEMPOOL_FRONTEND_DIR}/mempool-frontend-config.json"
MEMPOOL_SERVICE="mempool.service"
MEMPOOL_SERVICE_FILE="/etc/systemd/system/mempool.service"
MEMPOOL_WEBROOT_DIR="${NGINX_WEBROOT_DIR}/mempool"
MEMPOOL_NGINX_SSL_CONF="/etc/nginx/sites-available/mempool-ssl.conf"
MEMPOOL_NGINX_APP_CONF="${NGINX_SNIPPETS_DIR}/nginx-mempool.conf"
MEMPOOL_SSL_PORT="4080"

#-----------------------------------------------------------------

# LND config
LND_VERSION="0.18.1-beta"
LND_DIR="${HOME_DIR}/.lnd"
LND_DOWNLOAD_DIR="${DOWNLOAD_DIR}/Lnd"
LND_CONF_FILE="${LND_DIR}/lnd.conf"
LND_SERVICE="lnd.service"
LND_SERVICE_FILE="/etc/systemd/system/${LND_SERVICE}"
LND_CERT_FILE="${LND_DIR}/tls.cert"
LND_ADMIN_MACAROON_FILE="${LND_DIR}/data/chain/bitcoin/mainnet/admin.macaroon"
LND_READONLY_MACAROON_FILE="${LND_DIR}/data/chain/bitcoin/mainnet/readonly.macaroon"

#-----------------------------------------------------------------

# Thunderhub config
THH_VERSION="0.13.31"
THH_DIR="${HOME_DIR}/thunderhub"
THH_CONF_DIR="${HOME_DIR}/.thunderhub"
THH_ENV_CONF_FILE="${THH_DIR}/.env.local"
THH_YAML_CONF_FILE="${THH_CONF_DIR}/thubConfig.yaml"
THH_SERVICE="thunderhub.service"
THH_SERVICE_FILE="/etc/systemd/system/${THH_SERVICE}"
THH_NGINX_SSL_CONF="${NGINX_STREAMS_DIR}/thunderhub-ssl.conf"
THH_SSL_PORT="4001"

#-----------------------------------------------------------------

# Sparrow config
SPARROW_VERSION="1.9.1"
SPARROW_DIR="${HOME_DIR}/.sparrow"
SPARROW_DOWNLOAD_DIR="${DOWNLOAD_DIR}/Sparrow"
SPARROW_CONF_FILE="${SPARROW_DIR}/config"
SPARROW_LOG_FILE="${SPARROW_DIR}/sparrow.log"
SPARROW_APP_DIR="/opt/Sparrow"
SPARROW_SYM_LINK="/usr/local/bin/Sparrow"

#-----------------------------------------------------------------

# Bisq (headless) config
BISQ_VERSION="1.9.17"
BISQ_JAVA_VERSION="17"
BISQ_DOWNLOAD_DIR="${DOWNLOAD_DIR}/Bisq"
BISQ_APP_DIR="${HOME_DIR}/bisq"
BISQ_DATA_DIR="${HOME_DIR}/bisq-data"
BISQ_START_SCRIPT="${HOME_DIR}/start_bisq_xpra.sh"
BISQ_STOP_SCRIPT="${HOME_DIR}/stop_bisq_xpra.sh"
BISQ_LIST_FILE="${APT_SOURCES_DIR}/xpra_bisq.list"
BISQ_SSL_PORT="9876"
BISQ_SYM_LINK="/usr/local/bin/Bisq"

#-----------------------------------------------------------------

# Glances (system monitor) config
GLANCES_VERSION="4.1.1"
GLANCES_APP_DIR="/usr/local/bin"
GLANCES_SERVICE="glances.service"
GLANCES_SERVICE_FILE="/etc/systemd/system/${GLANCES_SERVICE}"
GLANCES_NGINX_SSL_CONF="/etc/nginx/streams-enabled/glances-ssl.conf"
GLANCES_SSL_PORT="4002"

#-----------------------------------------------------------------

# BTC RPC Explorer config
EXPLORER_VERSION="3.4.0"
EXPLORER_DIR="${HOME_DIR}/btc-rpc-explorer"
EXPLORER_CONF_FILE="${EXPLORER_DIR}/.env"
EXPLORER_SERVICE="explorer.service"
EXPLORER_SERVICE_FILE="/etc/systemd/system/${EXPLORER_SERVICE}"
EXPLORER_NGINX_SSL_CONF="${NGINX_STREAMS_DIR}/explorer-ssl.conf"
EXPLORER_SSL_PORT="4032"

#-----------------------------------------------------------------

# Bitfeed config
BITFEED_VERSION="2.3.4"
BITFEED_PKGS="erlang-dev elixir"
BITFEED_DIR="${HOME_DIR}/bitfeed"
BITFEED_BACKEND_DIR="${BITFEED_DIR}/server"
BITFEED_FRONTEND_DIR="${BITFEED_DIR}/client"
BITFEED_SERVICE="bitfeed.service"
BITFEED_SERVICE_FILE="/etc/systemd/system/${BITFEED_SERVICE}"
BITFEED_WEBROOT_DIR="${NGINX_WEBROOT_DIR}/bitfeed"
BITFEED_NGINX_SSL_CONF="/etc/nginx/sites-available/bitfeed-ssl.conf"
BITFEED_SSL_PORT="4041"

#-----------------------------------------------------------------

# Node Status Server Monitor config
NODE_STAT_PKGS="php-fpm php"
NODE_STAT_SERVICE="node_status.service"
NODE_STAT_SERVICE_FILE="/etc/systemd/system/${NODE_STAT_SERVICE}"
NODE_STAT_WEBROOT_DIR="${NGINX_WEBROOT_DIR}/node_status"
NODE_STAT_NGINX_SSL_CONF="/etc/nginx/sites-available/node_status-ssl.conf"
NODE_STAT_SSL_PORT="4021"

#-----------------------------------------------------------------

# Lightning Network Visualizer config
LNVIS_VERSION="0.0.28"
#LNVIS_PKGS="python make g++"
LNVIS_DIR="${HOME_DIR}/LN-Visualizer"
LNVIS_BACKEND_DIR="${LNVIS_DIR}/api"
LNVIS_FRONTEND_DIR="${LNVIS_DIR}"
LNVIS_BACKEND_CONF="${LNVIS_BACKEND_DIR}/config/default.json"
LNVIS_SERVICE="ln-visualizer.service"
LNVIS_SERVICE_FILE="/etc/systemd/system/${LNVIS_SERVICE}"
LNVIS_WEBROOT_DIR="${NGINX_WEBROOT_DIR}/ln-visualizer"
LNVIS_NGINX_SSL_CONF="/etc/nginx/sites-available/ln-visualizer-ssl.conf"
LNVIS_SSL_PORT="4071"

#-----------------------------------------------------------------

# Electrs config
ELECTRS_VERSION="0.10.5"
ELECTRS_PKGS="clang cmake build-essential"
ELECTRS_DIR="${HOME_DIR}/electrs"
ELECTRS_DATA_DIR="${HOME_DIR}/electrs_db"
ELECTRS_CONF_FILE="${ELECTRS_DIR}/electrs.conf"
ELECTRS_SERVICE="electrs.service"
ELECTRS_SERVICE_FILE="/etc/systemd/system/${ELECTRS_SERVICE}"
ELECTRS_NGINX_SSL_CONF="${NGINX_STREAMS_DIR}/electrs-ssl.conf"

#-----------------------------------------------------------------

# Ride the Lightning (RTL) config
RTL_VERSION="0.15.2"
RTL_DIR="${HOME_DIR}/RTL"
RTL_CONF_FILE="${RTL_DIR}/RTL-Config.json"
RTL_SERVICE="rtl.service"
RTL_SERVICE_FILE="/etc/systemd/system/${RTL_SERVICE}"
RTL_NGINX_SSL_CONF="${NGINX_STREAMS_DIR}/rtl-ssl.conf"
RTL_SSL_PORT="4010"

#-----------------------------------------------------------------

# JoinMarket / Jam config
JM_VERSION="0.9.11"
JM_PKGS="python3-dev python3-pip python3-virtualenv python3-venv build-essential automake pkg-config libtool libffi-dev libssl-dev libsodium-dev"
JM_DOWNLOAD_DIR="${DOWNLOAD_DIR}/Joinmarket"
JM_DIR="${HOME_DIR}/joinmarket"
JM_DATA_DIR="${HOME_DIR}/.joinmarket"
JM_CONF_FILE="${JM_DATA_DIR}/joinmarket.cfg"
JM_WALLETD_SERVICE="jmwalletd.service"
JM_OBWATCHER_SERVICE="obwatcher.service"
JM_WALLETD_SERVICE_FILE="/etc/systemd/system/${JM_WALLETD_SERVICE}"
JM_OBWATCHER_SERVICE_FILE="/etc/systemd/system/${JM_OBWATCHER_SERVICE}"
# ----------
JAM_VERSION="0.2.0"
JAM_DIR="${HOME_DIR}/jam"
JAM_CONF_FILE="${HOME_DIR}/jam/.env"
JAM_SERVICE="jam.service"
JAM_SERVICE_FILE="/etc/systemd/system/${JAM_SERVICE}"
JAM_NGINX_SSL_CONF="${NGINX_STREAMS_DIR}/jam-ssl.conf"
JAM_SSL_PORT="4020"

#-----------------------------------------------------------------

# BTCPay Server config
BTCPAY_DOTNET_VERSION="8.0"
BTCPAY_DOTNET_DIR="${HOME_DIR}/.dotnet"
BTCPAY_NBX_VERSION="2.4.3"
BTCPAY_NBX_DIR="${HOME_DIR}/NBXplorer"
BTCPAY_NBX_DATA_DIR="${HOME_DIR}/.nbxplorer"
BTCPAY_NBX_CONF_FILE="${BTCPAY_NBX_DATA_DIR}/Main/settings.config"
BTCPAY_NBX_SERVICE="nbxplorer.service"
BTCPAY_NBX_SERVICE_FILE="/etc/systemd/system/${BTCPAY_NBX_SERVICE}"
# ----------
BTCPAY_VERSION="1.13.1"
BTCPAY_PKGS="postgresql postgresql-contrib"
BTCPAY_DIR="${HOME_DIR}/btcpayserver"
BTCPAY_DATA_DIR="${HOME_DIR}/.btcpayserver"
BTCPAY_CONF_FILE="${BTCPAY_DATA_DIR}/Main/settings.config"
BTCPAY_LIST_FILE="${APT_SOURCES_DIR}/pgdg.list"
BTCPAY_SERVICE="btcpay.service"
BTCPAY_SERVICE_FILE="/etc/systemd/system/${BTCPAY_SERVICE}"
BTCPAY_NGINX_SSL_CONF="/etc/nginx/sites-available/btcpay-ssl.conf"
BTCPAY_SSL_PORT="4030"

#-----------------------------------------------------------------

# bash colors
# https://www.shellhacks.com/bash-colors/
# bash colors
BL="\033[0;30m"   # is Blacks's ANSI color code
R="\033[0;31m"    # is Red's ANSI color code
G="\033[0;32m"    # is Green's ANSI color code
BR="\033[0;33m"   # is Browns's ANSI color code
B="\033[0;34m"    # is Blue's ANSI color code
PU="\033[1;35m"   # is Purple's ANSI color code
CY="\033[1;36m"   # is Cyan's ANSI color code
LG="\033[1;37m"   # is Light Gray's ANSI color code

DG="\033[1;30m"   # is D-Gray's ANSI color code
LR="\033[1;31m"   # is L-Red's ANSI color code
LG="\033[1;32m"   # is L-Green's ANSI color code
Y="\033[1;33m"    # is Yellow's ANSI color code
LB="\033[1;34m"   # is L-Brown's ANSI color code
LP="\033[1;35m"   # is L-Purple's ANSI color code
LC="\033[1;36m"   # is L-Cyan's ANSI color code
WH="\033[1;37m"   # is White's ANSI color code

NC="\033[0m"      # No Color

#-----------------------------------------------------------------
